[0;34m[INFO][0m Applying server domain styles to card (desktop)
/**
 * Generated by Multi-Domain Component Build System
 * Component: card
 * Platform: desktop
 * Domain: server
 * Build Time: 2025-09-29T02:35:18Z
 * Source: components/global.c/desktop/card.js
 */

// Desktop Card Component
// Desktop-optimized card with hover states and refined interactions

class DesktopCard {
  constructor(options = {}) {
    this.options = {
      containerId: null,
      title: 'Card Title',
      description: 'Card description goes here',
      imageUrl: null,
      linkUrl: null,
      linkText: 'Learn More',
      variant: 'default', // default, featured, compact, horizontal
      showButton: true,
      interactive: true,
      width: 'auto', // auto, fixed, full
      ...options
    };
    
    this.init();
  }

  init() {
    this.render();
    if (this.options.interactive) {
      this.attachEventListeners();
    }
  }

  render() {
    const container = this.options.containerId ? 
      document.getElementById(this.options.containerId) : 
      document.createElement('div');
    
    const cardHTML = `
      <div class="card-desktop ${this.options.variant} ${this.options.width}" data-card-id="${this.generateId()}">
        ${this.renderCardContent()}
      </div>
      
      <style>
        .card-desktop {
          background: white;
          border-radius: 12px;
          box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
          border: 1px solid #e2e8f0;
          overflow: hidden;
          transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
          position: relative;
          cursor: pointer;
          display: flex;
          flex-direction: column;
        }
        
        .card-desktop:hover {
          transform: translateY(-4px);
          box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
          border-color: #cbd5e1;
        }
        
        .card-desktop:active {
          transform: translateY(-2px);
        }
        
        /* Variant styles */
        .card-desktop.featured {
          border: 2px solid #3b82f6;
          box-shadow: 0 4px 16px rgba(59, 130, 246, 0.15);
        }
        
        .card-desktop.featured:hover {
          box-shadow: 0 25px 35px -5px rgba(59, 130, 246, 0.2), 0 15px 15px -5px rgba(59, 130, 246, 0.1);
        }
        
        .card-desktop.compact {
          border-radius: 8px;
        }
        
        .card-desktop.compact .card-content {
          padding: 1.25rem;
        }
        
        .card-desktop.horizontal {
          flex-direction: row;
          min-height: 200px;
        }
        
        .card-desktop.horizontal .card-image {
          width: 300px;
          height: auto;
          flex-shrink: 0;
        }
        
        .card-desktop.horizontal .card-content {
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: space-between;
        }
        
        /* Width variants */
        .card-desktop.fixed {
          width: 320px;
        }
        
        .card-desktop.full {
          width: 100%;
        }
        
        /* Image styles */
        .card-image {
          width: 100%;
          height: 200px;
          object-fit: cover;
          display: block;
          transition: transform 0.3s ease;
        }
        
        .card-desktop:hover .card-image {
          transform: scale(1.05);
        }
        
        .card-image-container {
          overflow: hidden;
          position: relative;
        }
        
        .card-image-overlay {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: linear-gradient(to bottom, transparent 0%, rgba(0,0,0,0.1) 100%);
          opacity: 0;
          transition: opacity 0.3s ease;
        }
        
        .card-desktop:hover .card-image-overlay {
          opacity: 1;
        }
        
        .card-image-placeholder {
          width: 100%;
          height: 200px;
          background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
          display: flex;
          align-items: center;
          justify-content: center;
          color: #94a3b8;
          font-size: 0.875rem;
        }
        
        /* Content styles */
        .card-content {
          padding: 1.5rem;
          flex: 1;
          display: flex;
          flex-direction: column;
        }
        
        .card-header {
          margin-bottom: 1rem;
        }
        
        .card-title {
          font-size: 1.25rem;
          font-weight: 600;
          color: #1e293b;
          margin: 0 0 0.5rem 0;
          line-height: 1.4;
          transition: color 0.2s ease;
        }
        
        .card-desktop:hover .card-title {
          color: #3b82f6;
        }
        
        .card-subtitle {
          font-size: 0.875rem;
          color: #64748b;
          margin: 0;
          font-weight: 500;
        }
        
        .card-description {
          font-size: 0.9rem;
          color: #64748b;
          line-height: 1.6;
          margin: 0;
          flex-grow: 1;
        }
        
        .card-footer {
          margin-top: 1.25rem;
          display: flex;
          align-items: center;
          justify-content: space-between;
        }
        
        /* Button styles */
        .card-button {
          background: #3b82f6;
          color: white;
          border: none;
          padding: 0.625rem 1.25rem;
          border-radius: 6px;
          font-size: 0.875rem;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.2s ease;
          text-decoration: none;
          display: inline-flex;
          align-items: center;
          gap: 0.5rem;
        }
        
        .card-button:hover {
          background: #2563eb;
          transform: translateY(-1px);
          box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
        }
        
        .card-button:active {
          transform: translateY(0);
          background: #1d4ed8;
        }
        
        .card-button.secondary {
          background: transparent;
          color: #3b82f6;
          border: 1px solid #3b82f6;
        }
        
        .card-button.secondary:hover {
          background: #3b82f6;
          color: white;
        }
        
        .card-button.ghost {
          background: transparent;
          color: #64748b;
          border: none;
          padding: 0.5rem 0;
        }
        
        .card-button.ghost:hover {
          color: #3b82f6;
          background: transparent;
          transform: translateX(4px);
        }
        
        /* Meta information */
        .card-meta {
          display: flex;
          align-items: center;
          gap: 1rem;
          font-size: 0.8rem;
          color: #94a3b8;
        }
        
        .card-meta-item {
          display: flex;
          align-items: center;
          gap: 0.25rem;
        }
        
        /* Badge */
        .card-badge {
          position: absolute;
          top: 1rem;
          right: 1rem;
          background: #3b82f6;
          color: white;
          padding: 0.25rem 0.5rem;
          border-radius: 4px;
          font-size: 0.75rem;
          font-weight: 500;
        }
        
        .card-badge.success {
          background: #22c55e;
        }
        
        .card-badge.warning {
          background: #f59e0b;
        }
        
        .card-badge.danger {
          background: #ef4444;
        }
        
        /* Loading state */
        .card-desktop.loading {
          pointer-events: none;
          opacity: 0.7;
        }
        
        .card-desktop.loading::after {
          content: '';
          position: absolute;
          top: 50%;
          left: 50%;
          width: 24px;
          height: 24px;
          border: 2px solid #e2e8f0;
          border-top-color: #3b82f6;
          border-radius: 50%;
          animation: spin 1s linear infinite;
          transform: translate(-50%, -50%);
        }
        
        @keyframes spin {
          to { transform: translate(-50%, -50%) rotate(360deg); }
        }
        
        /* Focus states */
        .card-desktop:focus {
          outline: 2px solid #3b82f6;
          outline-offset: 2px;
        }
        
        /* Hide on mobile */
        @media (max-width: 768px) {
          .card-desktop {
            display: none;
          }
        }
        
        /* Responsive adjustments */
        @media (max-width: 1024px) {
          .card-desktop.horizontal {
            flex-direction: column;
          }
          
          .card-desktop.horizontal .card-image {
            width: 100%;
            height: 200px;
          }
        }
        
        /* Dark mode support */
        @media (prefers-color-scheme: dark) {
          .card-desktop {
            background: #1e293b;
            border-color: #334155;
          }
          
          .card-title {
            color: #f8fafc;
          }
          
          .card-description {
            color: #cbd5e1;
          }
          
          .card-subtitle {
            color: #94a3b8;
          }
          
          .card-desktop:hover {
            border-color: #475569;
          }
        }
      </style>
    `;
    
    if (this.options.containerId) {
      container.innerHTML = cardHTML;
    } else {
      container.innerHTML = cardHTML;
      return container;
    }
  }

  renderCardContent() {
    return `
      ${this.renderBadge()}
      ${this.options.imageUrl ? this.renderImage() : ''}
      <div class="card-content">
        <div class="card-header">
          <h3 class="card-title">${this.options.title}</h3>
          ${this.options.subtitle ? `<p class="card-subtitle">${this.options.subtitle}</p>` : ''}
        </div>
        <p class="card-description">${this.options.description}</p>
        ${this.renderFooter()}
      </div>
    `;
  }

  renderImage() {
    if (this.options.imageUrl) {
      return `
        <div class="card-image-container">
          <img 
            src="${this.options.imageUrl}" 
            alt="${this.options.title}"
            class="card-image"
            loading="lazy"
          />
          <div class="card-image-overlay"></div>
        </div>
      `;
    } else {
      return `
        <div class="card-image-placeholder">
          <svg width="56" height="56" viewBox="0 0 24 24" fill="currentColor">
            <path d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z"/>
          </svg>
        </div>
      `;
    }
  }

  renderFooter() {
    if (!this.options.showButton && !this.options.meta) return '';
    
    return `
      <div class="card-footer">
        ${this.options.meta ? this.renderMeta() : '<div></div>'}
        ${this.options.showButton ? this.renderButton() : ''}
      </div>
    `;
  }

  renderButton() {
    if (this.options.linkUrl) {
      return `
        <a href="${this.options.linkUrl}" class="card-button">
          ${this.options.linkText}
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
            <path d="M7.33 24l-2.83-2.829 9.339-9.175-9.339-9.167 2.83-2.829 12.17 11.996z"/>
          </svg>
        </a>
      `;
    } else {
      return `
        <button class="card-button" data-action="click">
          ${this.options.linkText}
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
            <path d="M7.33 24l-2.83-2.829 9.339-9.175-9.339-9.167 2.83-2.829 12.17 11.996z"/>
          </svg>
        </button>
      `;
    }
  }

  renderMeta() {
    if (!this.options.meta) return '';
    
    return `
      <div class="card-meta">
        ${this.options.meta.map(item => `
          <div class="card-meta-item">
            ${item.icon ? `<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor">${item.icon}</svg>` : ''}
            <span>${item.text}</span>
          </div>
        `).join('')}
      </div>
    `;
  }

  renderBadge() {
    if (!this.options.badge) return '';
    
    return `
      <div class="card-badge ${this.options.badge.type || ''}">
        ${this.options.badge.text}
      </div>
    `;
  }

  attachEventListeners() {
    const card = document.querySelector(`[data-card-id="${this.generateId()}"]`);
    const button = card?.querySelector('.card-button');
    
    if (card && this.options.interactive) {
      // Card click handling
      card.addEventListener('click', (e) => {
        // Don't trigger card click if button was clicked
        if (!e.target.closest('.card-button')) {
          this.onCardClick(e);
        }
      });
      
      // Keyboard navigation
      card.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          this.onCardClick(e);
        }
      });
      
      // Make card focusable
      card.setAttribute('tabindex', '0');
    }
    
    if (button && !this.options.linkUrl) {
      button.addEventListener('click', (e) => {
        e.stopPropagation();
        this.onButtonClick(e);
      });
    }
    
    // Handle image loading errors
    const image = card?.querySelector('.card-image');
    if (image) {
      image.addEventListener('error', () => {
        const container = image.parentElement;
        container.innerHTML = `
          <div class="card-image-placeholder">
            <svg width="56" height="56" viewBox="0 0 24 24" fill="currentColor">
              <path d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z"/>
            </svg>
          </div>
        `;
      });
    }
  }

  onCardClick(event) {
    // Default card click behavior
    if (this.options.linkUrl) {
      window.open(this.options.linkUrl, '_blank');
    } else {
      // Fire custom event
      const customEvent = new CustomEvent('cardClick', {
        detail: { 
          cardId: this.generateId(),
          title: this.options.title,
          options: this.options 
        }
      });
      document.dispatchEvent(customEvent);
    }
  }

  onButtonClick(event) {
    // Default button click behavior
    const customEvent = new CustomEvent('cardButtonClick', {
      detail: { 
        cardId: this.generateId(),
        title: this.options.title,
        options: this.options 
      }
    });
    document.dispatchEvent(customEvent);
  }

  generateId() {
    if (!this._id) {
      this._id = 'card-' + Math.random().toString(36).substr(2, 9);
    }
    return this._id;
  }

  setLoading(isLoading) {
    const card = document.querySelector(`[data-card-id="${this.generateId()}"]`);
    if (card) {
      if (isLoading) {
        card.classList.add('loading');
      } else {
        card.classList.remove('loading');
      }
    }
  }

  updateContent(newOptions) {
    this.options = { ...this.options, ...newOptions };
    
    const card = document.querySelector(`[data-card-id="${this.generateId()}"]`);
    if (card) {
      const title = card.querySelector('.card-title');
      const description = card.querySelector('.card-description');
      const button = card.querySelector('.card-button');
      const image = card.querySelector('.card-image');
      
      if (title && newOptions.title) title.textContent = newOptions.title;
      if (description && newOptions.description) description.textContent = newOptions.description;
      if (button && newOptions.linkText) button.textContent = newOptions.linkText;
      if (image && newOptions.imageUrl) image.src = newOptions.imageUrl;
    }
  }

  setVariant(variant) {
    const card = document.querySelector(`[data-card-id="${this.generateId()}"]`);
    if (card) {
      card.classList.remove('default', 'featured', 'compact', 'horizontal');
      card.classList.add(variant);
      this.options.variant = variant;
    }
  }

  destroy() {
    const card = document.querySelector(`[data-card-id="${this.generateId()}"]`);
    if (card) {
      card.remove();
    }
  }

  // Static method to create a grid of cards
  static createGrid(cardsData, containerSelector, columns = 3) {
    const container = document.querySelector(containerSelector);
    if (!container) return [];
    
    // Add grid styles
    container.style.display = 'grid';
    container.style.gridTemplateColumns = `repeat(auto-fit, minmax(300px, 1fr))`;
    container.style.gap = '1.5rem';
    
    const cards = [];
    cardsData.forEach((cardData, index) => {
      const cardElement = document.createElement('div');
      cardElement.id = `desktop-card-${index}`;
      container.appendChild(cardElement);
      
      const card = new DesktopCard({
        ...cardData,
        containerId: cardElement.id
      });
      cards.push(card);
    });
    
    return cards;
  }
}

// Export for module use
if (typeof module !== 'undefined' && module.exports) {
  module.exports = DesktopCard;
}
